#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"
##############
# Essentials #
##############

# Truncate a couple of common commands that are used herein.
# _bc() {
# 	bspc config "$@"
# }

_check() {
	command -v "$1" > /dev/null
}

# Determine XrandR settings.  Whether an external display is connected
# to the laptop or not.
_check bspwm_conf_xrandr && bspwm_conf_xrandr

# Defin desktop[s] [per monitor].  Contingent on the above.  Also note
# that this leverages my `bspwm_dynamic_desktops'.
_check bspwm_conf_desktops && bspwm_conf_desktops

unfocused=#3A2F3F
focused=#FF3CFF
select=#FF3CFF
padding=0

# for side in top right bottom left; do
# 		bspc config ${side}_padding $padding
# done


bspc config normal_border_color			$unfocused
bspc config active_border_color			$unfocused
bspc config focused_border_color		$focused
bspc config presel_feedback_color		$select
bspc config border_width    		    1
bspc config window_gap          		0
bspc config split_ratio          		0.5
bspc config borderless_monocle   		true
bspc config gapless_monocle      		true
bspc config borderless_monocle          false
bspc config focus_follows_pointer		true
bspc config paddingless_monocle			true
bspc config single_monocle  			true
bspc config pointer_modifier shift


# RULES

# dropdownname="dropdown"
# bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
# bspc rule -a St:$dropdownname hidden=on
# bspc rule -a St:$dropdownname sticky=on
# bspc rule -a St:$dropdownname state=floating

bspc rule -a St follow=on desktop='^1'
bspc rule -a qutebrowser follow=on desktop='^2'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a mpv state=floating follow=on sticky=on
#bspc rule -a Steam desktop='^7' state=tiled follow=off
#bspc rulw -a Spotify:spotify desktop='^2' state=tiled follow=off
#bspc rule -a Discord desktop='^8'
#bspc rule -a obs:obs desktop='^3'
#bspc rule -a chatty-Chatty:chatty-Chatty desktop='^8' state=tiled follow=off
#bspc rule -a Blueberry.py state=floating follow=off
#bspc rule -a streamlink-twitch-gui state=floating follow=off
#bspc ruke -a pavucontrol desktop='^9'
#bspc rule -a Screenkey manage=off
bspc config external_rules_command $(which bspwm_rules)

_check  sxhkd && sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc{,_bspc} &

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
#pgrep -x panel > /dev/null || panel &
# Launch my custom Lemonbar implementation (the system panel).
if _check panel; then
	# Make sure we have no running instances
	pgrep -x panel && pkill -x panel
	panel &

    # Add padding equal to the panel height to fix an issue where there
    # is an overlap between panel and windows in monitor LVDS1.  The
    # panel gets covered by the windows.  This only happens when an
    # external monitor is connected to my laptop, for reasons that I
    # cannot determine…
    # if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
    #     _panel_height() {
    #         awk -F '=' '/melonpanel_height/ { print $2; exit; }' \
    #             $(command -v melonpanel)
    #     }
    #
	   #  bspc config bottom_padding "$(_panel_height)"
    # fi
fi
